### ISSUE TITLE
针对于中文数据genius_utils.py里面template==4的一个小问题

### ISSUE THREAD

**Issue by taishan1994** [beyondguo/genius#1]
针对中文，有个问题是在genius_utils.py里面template==4时：
输入：银色的罗马高跟鞋，圆球吊饰耳饰单带，个性十足，有非常抢眼！
得到：银色罗马高跟鞋圆球吊饰耳饰单带个性十足[MASK]抢眼[MASK]
也就是当两个关键词中间隔一个字时会省略掉。
不知道是故意如此还是有点问题，如果改成：

```python
if sep == '' and id - all_ids[i - 1] == 2: # a space in between
    masked_text.append(s[id-1])

```
得到：银色的罗马高跟鞋，圆球吊饰耳饰单带，个性十足[MASK]抢眼[MASK]

**Comment by beyondguo** [comment]
Hi, you are right, this is a bug. I have fixed it in the latest commit. Thanks for pointing that out! 🤝 🤝

btw, your fix may not be correct, since the punctuation should be included in the sketch. Please check my latest code.
Here's your case after the update:
```python
zh_SE = SketchExtractor('jieba')
t = """银色的罗马高跟鞋，圆球吊饰耳饰单带，个性十足，有非常抢眼！"""
_, kws = zh_SE.get_kws(t)
kws
<<< ['吊饰', '耳饰', '单带', '圆球', '高跟鞋', '银色', '抢眼', '十足', '个性', '罗马']
zh_SE.get_sketch_from_kws(t2,kws)
<<< '银色[mask]罗马高跟鞋[mask]圆球吊饰耳饰单带[mask]个性十足[mask]抢眼[mask]'
```


(the `genius_utils.py` has been changed a lot of times after the `genius-base-chinese` model pre-training, I think during the training we didn't have this problem, so the pre-trained model is not affected)
